import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../core/models.dart';
import '../../theme/stitch_theme.dart';
import '../../utils/widgets.dart';

class EWayBillSlipScreen extends StatelessWidget {
  const EWayBillSlipScreen({
    super.key,
    required this.business,
    required this.invoice,
    this.customer,
  });

  final Business business;
  final Invoice invoice;
  final Customer? customer;

  Future<void> _printOrShare(BuildContext context) async {
    try {
      final doc = pw.Document();
      final ewbNo = invoice.ewayBillNumber ?? '241049281092';
      final validUntil = invoice.ewbValidUntil ?? '24 Hours';
      final ewbDate = invoice.ewbDate ?? invoice.date;

      doc.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(24),
          build: (pw.Context ctx) {
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Center(
                  child: pw.Column(
                    children: [
                      pw.Text('e-Way Bill System', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                      pw.SizedBox(height: 2),
                      pw.Text('Government of India', style: const pw.TextStyle(fontSize: 11)),
                      pw.SizedBox(height: 2),
                      pw.Text('Form GST EWB-01', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
                      pw.Text('(See Rule 138 of the Central Goods and Services Tax Rules, 2017)', style: const pw.TextStyle(fontSize: 8)),
                    ],
                  ),
                ),
                pw.SizedBox(height: 14),
                pw.Center(
                  child: pw.BarcodeWidget(
                    barcode: pw.Barcode.code128(),
                    data: ewbNo,
                    width: 200,
                    height: 40,
                  ),
                ),
                pw.SizedBox(height: 6),
                pw.Center(
                  child: pw.Text('e-Way Bill No: $ewbNo', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
                ),
                pw.SizedBox(height: 14),

                // EWB Header Info Table
                pw.Table(
                  border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
                  children: [
                    pw.TableRow(
                      children: [
                        _pdfCell('e-Way Bill Date', ewbDate),
                        _pdfCell('Generated By', business.gstin ?? 'Unregistered'),
                      ],
                    ),
                    pw.TableRow(
                      children: [
                        _pdfCell('Valid From', ewbDate),
                        _pdfCell('Valid Until', validUntil),
                      ],
                    ),
                  ],
                ),
                pw.SizedBox(height: 14),

                // Part A Table
                pw.Container(
                  color: PdfColors.grey200,
                  padding: const pw.EdgeInsets.all(4),
                  child: pw.Text('PART - A', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold)),
                ),
                pw.Table(
                  border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
                  children: [
                    pw.TableRow(children: [_pdfCell('GSTIN of Supplier', business.gstin ?? 'Unregistered'), _pdfCell('Supplier Name', business.name)]),
                    pw.TableRow(children: [_pdfCell('GSTIN of Recipient', customer?.gstin ?? 'Unregistered'), _pdfCell('Recipient Name', customer?.name ?? invoice.customerName ?? 'Buyer')]),
                    pw.TableRow(children: [_pdfCell('Place of Delivery', invoice.shipToAddress ?? customer?.address ?? business.city ?? 'Commercial Destination'), _pdfCell('Document No. & Date', '${invoice.number} dt. ${invoice.date}')]),
                    pw.TableRow(children: [_pdfCell('Value of Goods', 'INR ${(invoice.total / 100).toStringAsFixed(2)}'), _pdfCell('HSN Code', invoice.lines.isNotEmpty ? (invoice.lines.first.hsn ?? '84705000') : '84705000')]),
                    pw.TableRow(children: [_pdfCell('Reason for Transportation', 'Outward Supply - Tax Invoice'), _pdfCell('Transporter', invoice.transporterName ?? 'Direct Transport')]),
                  ],
                ),
                pw.SizedBox(height: 14),

                // Part B Table
                pw.Container(
                  color: PdfColors.grey200,
                  padding: const pw.EdgeInsets.all(4),
                  child: pw.Text('PART - B (Vehicle / Transport Details)', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold)),
                ),
                pw.Table(
                  border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
                  children: [
                    pw.TableRow(
                      decoration: const pw.BoxDecoration(color: PdfColors.grey100),
                      children: [
                        _pdfHeader('Mode'),
                        _pdfHeader('Vehicle No'),
                        _pdfHeader('From'),
                        _pdfHeader('Entered Date'),
                        _pdfHeader('CEWB No (if any)'),
                      ],
                    ),
                    pw.TableRow(
                      children: [
                        _pdfCellRaw('Road'),
                        _pdfCellRaw(invoice.vehicleNumber ?? 'KA01AB1234'),
                        _pdfCellRaw(business.city ?? 'City'),
                        _pdfCellRaw(ewbDate),
                        _pdfCellRaw('-'),
                      ],
                    ),
                  ],
                ),
              ],
            );
          },
        ),
      );

      await Printing.layoutPdf(
        onLayout: (format) async => doc.save(),
        name: 'EWB_${invoice.ewayBillNumber ?? invoice.number}.pdf',
      );
    } catch (e) {
      if (context.mounted) {
        showAppMessage(context, 'PDF generation error: $e', error: true);
      }
    }
  }

  pw.Widget _pdfCell(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(5),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(label, style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700)),
          pw.SizedBox(height: 2),
          pw.Text(value, style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }

  pw.Widget _pdfHeader(String label) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(4),
      child: pw.Text(label, style: pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold)),
    );
  }

  pw.Widget _pdfCellRaw(String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(4),
      child: pw.Text(value, style: const pw.TextStyle(fontSize: 8)),
    );
  }

  @override
  Widget build(BuildContext context) {
    final ewbNo = invoice.ewayBillNumber ?? '—';
    final ewbDate = invoice.ewbDate ?? invoice.date;
    final validUntil = invoice.ewbValidUntil ?? '—';
    final vehicleNo = invoice.vehicleNumber ?? '—';

    return Scaffold(
      appBar: AppBar(
        title: const Text('Form GST EWB-01 Slip'),
        actions: [
          IconButton(
            icon: const Icon(Icons.print_outlined),
            tooltip: 'Print / Share Slip',
            onPressed: () => _printOrShare(context),
          ),
        ],
      ),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          // Official Slip Card
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: Colors.grey.shade300),
              boxShadow: const [
                BoxShadow(color: Color(0x08000000), blurRadius: 10, offset: Offset(0, 4)),
              ],
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                const Text(
                  'e-Way Bill System',
                  style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: StitchColors.textPrimary),
                ),
                const Text(
                  'Government of India',
                  style: TextStyle(fontSize: 12, color: StitchColors.textSecondary),
                ),
                const SizedBox(height: 2),
                const Text(
                  'Form GST EWB-01',
                  style: TextStyle(fontSize: 13, fontWeight: FontWeight.w800, color: StitchColors.primary),
                ),
                const Text(
                  '(See Rule 138 of CGST Rules, 2017)',
                  style: TextStyle(fontSize: 10, color: StitchColors.textTertiary),
                ),
                const SizedBox(height: 16),

                // 12-Digit EWB Pill
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                  decoration: BoxDecoration(
                    color: const Color(0xFFEFF6FF),
                    borderRadius: BorderRadius.circular(10),
                    border: Border.all(color: const Color(0xFFBFDBFE)),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      const Text(
                        'e-Way Bill No: ',
                        style: TextStyle(fontSize: 13, color: Color(0xFF1E40AF), fontWeight: FontWeight.w600),
                      ),
                      SelectableText(
                        ewbNo,
                        style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w800, letterSpacing: 0.8, color: Color(0xFF1E3A8A)),
                      ),
                      const SizedBox(width: 8),
                      GestureDetector(
                        onTap: () {
                          Clipboard.setData(ClipboardData(text: ewbNo));
                          showAppMessage(context, 'E-Way Bill Number copied ✓');
                        },
                        child: const Icon(Icons.copy_rounded, size: 16, color: Color(0xFF2563EB)),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 16),

                _buildTable([
                  ['e-Way Bill Date', ewbDate, 'Generated By', business.gstin ?? 'Unregistered'],
                  ['Valid From', ewbDate, 'Valid Until', validUntil],
                ]),
                const SizedBox(height: 16),

                // Part A
                _buildSectionHeader('PART - A (Goods Details)'),
                _buildTable([
                  ['GSTIN of Supplier', business.gstin ?? 'Unregistered', 'Supplier Name', business.name],
                  ['GSTIN of Recipient', customer?.gstin ?? 'Unregistered', 'Recipient Name', customer?.name ?? invoice.customerName ?? 'Buyer'],
                  ['Place of Delivery', invoice.shipToAddress ?? customer?.address ?? business.city ?? 'Commercial Destination', 'Doc No & Date', '${invoice.number} dt. ${invoice.date}'],
                  ['Value of Goods', '₹${(invoice.total / 100).toStringAsFixed(2)}', 'HSN Code', invoice.lines.isNotEmpty ? (invoice.lines.first.hsn ?? '84705000') : '84705000'],
                  ['Reason for Transport', 'Outward Supply - Tax Invoice', 'Transporter', invoice.transporterName ?? 'Direct Transport'],
                ]),
                const SizedBox(height: 16),

                // Part B
                _buildSectionHeader('PART - B (Vehicle Details)'),
                _buildTable([
                  ['Mode', 'Road', 'Vehicle No', vehicleNo],
                  ['From', business.city ?? 'City', 'Entered Date', ewbDate],
                ]),
              ],
            ),
          ),
          const SizedBox(height: 20),

          FilledButton.icon(
            style: FilledButton.styleFrom(
              minimumSize: const Size.fromHeight(50),
              backgroundColor: StitchColors.primary,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            ),
            icon: const Icon(Icons.print_rounded),
            label: const Text('Print / Share Government Slip', style: TextStyle(fontSize: 15, fontWeight: FontWeight.w700)),
            onPressed: () => _printOrShare(context),
          ),
        ],
      ),
    );
  }

  Widget _buildSectionHeader(String title) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
      margin: const EdgeInsets.only(bottom: 6),
      decoration: BoxDecoration(
        color: const Color(0xFFF1F5F9),
        borderRadius: BorderRadius.circular(6),
      ),
      child: Text(title, style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w800, color: StitchColors.textPrimary)),
    );
  }

  Widget _buildTable(List<List<String>> rows) {
    return Container(
      decoration: BoxDecoration(
        border: Border.all(color: Colors.grey.shade200),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Column(
        children: rows.map((r) {
          return Container(
            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
            decoration: BoxDecoration(
              border: Border(bottom: BorderSide(color: Colors.grey.shade100)),
            ),
            child: Row(
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(r[0], style: const TextStyle(fontSize: 11, color: StitchColors.textSecondary)),
                      const SizedBox(height: 2),
                      Text(r[1], style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w700, color: StitchColors.textPrimary)),
                    ],
                  ),
                ),
                if (r.length >= 4)
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(r[2], style: const TextStyle(fontSize: 11, color: StitchColors.textSecondary)),
                        const SizedBox(height: 2),
                        Text(r[3], style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w700, color: StitchColors.textPrimary)),
                      ],
                    ),
                  ),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }
}
